import manifest from './cloudinaryManifest.json'

const CLOUD_NAME = process.env.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME || ''
const BASE = CLOUD_NAME ? `https://res.cloudinary.com/${CLOUD_NAME}` : ''

/**
 * The site stores image paths as local public paths (`/gallery/Steel Gates/x.jpg`),
 * sometimes percent-encoded (`/gallery/Steel%20Gates/x.jpg`). Normalise both
 * forms to the decoded path used as the manifest key.
 */
function normalise(src) {
    if (typeof src !== 'string') return ''
    let out = src
    try {
        out = decodeURIComponent(src)
    } catch {
        /* malformed escape - fall back to the raw string */
    }
    return out.startsWith('/') ? out : `/${out}`
}

function lookup(src) {
    const key = normalise(src)
    return manifest[key] || null
}

/** True once the upload script has run and a cloud name is configured. */
export const isCloudinaryEnabled = Boolean(CLOUD_NAME) && Object.keys(manifest).length > 0

/**
 * Resolve a local public path to a Cloudinary delivery URL.
 *
 * Falls back to the original local path when the asset has not been uploaded or
 * no cloud name is set, so the site keeps working before/independently of the
 * migration.
 *
 * @param {string} src   local public path, e.g. '/gallery/Steel Gates/x.jpg'
 * @param {object} [opts]
 * @param {number} [opts.width]   target width in px (w_)
 * @param {number} [opts.height]  target height in px (h_)
 * @param {number} [opts.quality] 1-100, omit for q_auto
 * @param {string} [opts.crop]    default 'limit' - never upscale
 * @param {string} [opts.gravity] e.g. 'auto', only meaningful with a cropping mode
 * @param {boolean} [opts.dpr]    default true (dpr_auto). Pass false when the
 *                                caller emits its own 2x srcset, so the density
 *                                is not applied twice.
 */
export function cld(src, opts = {}) {
    const entry = lookup(src)
    if (!entry || !BASE) return src

    if (entry.resourceType === 'raw') {
        return `${BASE}/raw/upload/v${entry.version}/${entry.publicId}`
    }

    /*
     * Video takes f_auto,q_auto and nothing else. The image transforms below
     * are the wrong vocabulary for it - dpr_auto has no meaning for a clip, and
     * c_limit on a video re-encodes the whole file rather than cropping a
     * frame. f_auto alone is what takes a phone clip from ~15 MB to under 3 MB
     * and hands VP9 or AV1 to browsers that can decode them.
     */
    if (entry.resourceType === 'video') {
        const v = ['f_auto', opts.quality ? `q_${opts.quality}` : 'q_auto']
        // Only width, and always c_limit so a clip is never scaled up. This
        // matters whenever the source is bigger than its slot, which is the
        // normal case for a 720x1280 phone video in a 250px tile.
        if (opts.width) v.push(`w_${Math.round(opts.width)}`, 'c_limit')
        return `${BASE}/video/upload/${v.join(',')}/v${entry.version}/${entry.publicId}`
    }

    const t = ['f_auto', opts.quality ? `q_${opts.quality}` : 'q_auto']
    if (opts.width) t.push(`w_${Math.round(opts.width)}`)
    if (opts.height) t.push(`h_${Math.round(opts.height)}`)
    if (opts.width || opts.height) t.push(`c_${opts.crop || 'limit'}`)
    if (opts.gravity) t.push(`g_${opts.gravity}`)
    if (opts.dpr !== false) t.push('dpr_auto')

    return `${BASE}/image/upload/${t.join(',')}/v${entry.version}/${entry.publicId}`
}

/** Intrinsic dimensions recorded at upload time, or null if unknown. */
export function cldSize(src) {
    const entry = lookup(src)
    if (!entry || !entry.width || !entry.height) return null
    return { width: entry.width, height: entry.height }
}

/** Cloudinary URL for a catalogue PDF (raw resource), or the local path. */
export function cldFile(src) {
    const entry = lookup(src)
    if (!entry || !BASE) return src
    const kind = entry.resourceType === 'raw' ? 'raw' : 'image'
    return `${BASE}/${kind}/upload/v${entry.version}/${entry.publicId}`
}

/**
 * Poster frame for a video, grabbed at one second (`so_1`) and delivered as a
 * still image. A clip's first frame is often the lens still focusing, so one
 * second in is a more reliable thumbnail than zero.
 *
 * Returns undefined when the clip has not been uploaded yet, which is the
 * signal for a caller to fall back to its own poster or to none - a <video>
 * with no poster paints its first decoded frame instead.
 *
 * @param {string} src    local public path of the video
 * @param {number} [width] poster width in px, default 720
 */
export function cldPoster(src, width = 720) {
    const entry = lookup(src)
    if (!entry || !BASE || entry.resourceType !== 'video') return undefined
    return `${BASE}/video/upload/so_1,f_auto,q_auto,w_${Math.round(width)}/v${entry.version}/${entry.publicId}.jpg`
}

/**
 * A tiny blurred placeholder generated by Cloudinary, for use as
 * next/image `blurDataURL`. Returns undefined when unavailable.
 */
export function cldBlurUrl(src) {
    const entry = lookup(src)
    if (!entry || !BASE || entry.resourceType === 'raw') return undefined
    return `${BASE}/image/upload/f_auto,q_10,w_24,e_blur:200/v${entry.version}/${entry.publicId}`
}
