import manifest from './cloudinaryManifest.json'

const CLOUD_NAME = process.env.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME || ''
const BASE = CLOUD_NAME ? `https://res.cloudinary.com/${CLOUD_NAME}` : ''

/**
 * The site stores image paths as local public paths (`/gallery/Steel Gates/x.jpg`),
 * sometimes percent-encoded (`/gallery/Steel%20Gates/x.jpg`). Normalise both
 * forms to the decoded path used as the manifest key.
 */
function normalise(src) {
    if (typeof src !== 'string') return ''
    let out = src
    try {
        out = decodeURIComponent(src)
    } catch {
        /* malformed escape — fall back to the raw string */
    }
    return out.startsWith('/') ? out : `/${out}`
}

function lookup(src) {
    const key = normalise(src)
    return manifest[key] || null
}

/** True once the upload script has run and a cloud name is configured. */
export const isCloudinaryEnabled = Boolean(CLOUD_NAME) && Object.keys(manifest).length > 0

/**
 * Resolve a local public path to a Cloudinary delivery URL.
 *
 * Falls back to the original local path when the asset has not been uploaded or
 * no cloud name is set, so the site keeps working before/independently of the
 * migration.
 *
 * @param {string} src   local public path, e.g. '/gallery/Steel Gates/x.jpg'
 * @param {object} [opts]
 * @param {number} [opts.width]   target width in px (w_)
 * @param {number} [opts.height]  target height in px (h_)
 * @param {number} [opts.quality] 1-100, omit for q_auto
 * @param {string} [opts.crop]    default 'limit' — never upscale
 * @param {string} [opts.gravity] e.g. 'auto', only meaningful with a cropping mode
 * @param {boolean} [opts.dpr]    default true (dpr_auto). Pass false when the
 *                                caller emits its own 2x srcset, so the density
 *                                is not applied twice.
 */
export function cld(src, opts = {}) {
    const entry = lookup(src)
    if (!entry || !BASE) return src

    if (entry.resourceType === 'raw') {
        return `${BASE}/raw/upload/v${entry.version}/${entry.publicId}`
    }

    const t = ['f_auto', opts.quality ? `q_${opts.quality}` : 'q_auto']
    if (opts.width) t.push(`w_${Math.round(opts.width)}`)
    if (opts.height) t.push(`h_${Math.round(opts.height)}`)
    if (opts.width || opts.height) t.push(`c_${opts.crop || 'limit'}`)
    if (opts.gravity) t.push(`g_${opts.gravity}`)
    if (opts.dpr !== false) t.push('dpr_auto')

    return `${BASE}/image/upload/${t.join(',')}/v${entry.version}/${entry.publicId}`
}

/** Intrinsic dimensions recorded at upload time, or null if unknown. */
export function cldSize(src) {
    const entry = lookup(src)
    if (!entry || !entry.width || !entry.height) return null
    return { width: entry.width, height: entry.height }
}

/** Cloudinary URL for a catalogue PDF (raw resource), or the local path. */
export function cldFile(src) {
    const entry = lookup(src)
    if (!entry || !BASE) return src
    const kind = entry.resourceType === 'raw' ? 'raw' : 'image'
    return `${BASE}/${kind}/upload/v${entry.version}/${entry.publicId}`
}

/**
 * A tiny blurred placeholder generated by Cloudinary, for use as
 * next/image `blurDataURL`. Returns undefined when unavailable.
 */
export function cldBlurUrl(src) {
    const entry = lookup(src)
    if (!entry || !BASE || entry.resourceType === 'raw') return undefined
    return `${BASE}/image/upload/f_auto,q_10,w_24,e_blur:200/v${entry.version}/${entry.publicId}`
}
